// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iteummnhpclsvoppfqyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZXVtbW5ocGNsc3ZvcHBmcXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODAzMDIsImV4cCI6MjA2NTU1NjMwMn0.W0r4OkOYMZD8QyU-u__-SwJpAeNbor0EGQRoQS4Jflo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);